### ISSUE TITLE
"The string to be encoded contains characters outside of the Latin1 range"

### ISSUE THREAD

**Issue by paulocoghi** [ractivejs/ractive-load#24]
When loading a component file with `Ractive.load`, when I put a character like a curly quote ’ inside the HTML section, there is a possible bug occurring when the same component has a `<script>` tag.

The component below will render normally:

```html
<!-- components/something.html  -->
<div>
    This is my HTML section in my component file.
    And this is a buggy curly quote ’
</div>
```

But this one will not render:

```html
<!-- components/something.html  -->
<div>
    This is my HTML section in my component file.
    And this is a buggy curly quote ’
</div>

<script> </script>
```

And return the error:
> DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

>     code: 5
>     message: "Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range."
>     name: "InvalidCharacterError"
>     stack: "Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.↵    at Error (native)↵    at e (http://local.burh.com.br/javascript/ractive-load.min.js:1:2223)↵    at new e.Function (http://local.burh.com.br/javascript/ractive-load.min.js:1:3406)↵    at f (http://local.burh.com.br/javascript/ractive-load.min.js:1:4664)↵    at v (http://local.burh.com.br/javascript/ractive-load.min.js:1:5030)↵    at http://local.burh.com.br/javascript/ractive-load.min.js:1:5319↵    at http://local.burh.com.br/javascript/ractive.min.js:11:5960↵    at http://local.burh.com.br/javascript/ractive.min.js:11:5191"
>     __proto__: DOMException

Of course I removed the buggy character but I just want to understand the error. Is this charset limitation made by my browser or can I workaround it?

Just to note, my main page has a `UTF-8` charset in meta tag.

**Comment by martypdx** [comment]
I believe the bug is in `eval2` in ractive/rcu and was introduced when the sourcemaps changed from url to encoded sourcemaps. I don't know if the encoding just needs to be broader. Or if rcu needs to allow ractive-load to pass in the file option [here](https://github.com/ractivejs/rcu/commit/197fa94eea7ab3acf76422abbdd4139acad10906). Or maybe both.

**Comment by paulocoghi** [comment]
If you consider important, I can submit this issue in rcu repo.
