### ISSUE TITLE
Official download link not working

### ISSUE THREAD

**Issue by paulocoghi** [ractivejs/ractive-load#27]
In official Ractive Load page http://ractivejs.github.io/ractive-load/ , the download link doesn't work correctly, returning 'Not found'.

https://raw.githubusercontent.com/ractivejs/ractive-load/master/ractive-load.js

**Comment by martypdx** [comment]
updated link to: https://raw.githubusercontent.com/ractivejs/ractive-load/master/dist/lib/ractive-load.js

@Rich-Harris there's two files in dist, I choose this one because it's newer.
