### ISSUE TITLE
Does ractive-load works with edge?

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive-load#37]
Hi, how to make this work with Ractive 0.8 edge?

**Comment by martypdx** [comment]
ractive-load [has an edge branch](https://github.com/ractivejs/ractive-load/tree/edge) as well. (Full disclosure: haven't tried it myself).

**Comment by kouts** [comment]
Thanks @martypdx I will try that, what tools do I need to build it?

**Comment by dagnelies** [comment]
No, it does not work with edge. It is outdated and would trigger: https://github.com/ractivejs/ractive/issues/2570

**Comment by kouts** [comment]
Ok so I managed to make ractive-load work with Ractive 0.8 edge.
I did a local build and replaced dependencies "rcu" with
```
"rcu": "^0.9.0-edge1"
```
and devDependencies "ractive" with
```
"ractive": "git+https://github.com/ractivejs/ractive.git#edge"
```

**Comment by dagnelies** [comment]
Hooray! 👍 🎉 🎉 🎉 ...That was time!

**Comment by fskreuz** [comment]
You can thank @evs-chris for reminding me 😁
