### ISSUE TITLE
ractive 0.8.0 Error: Mismatched template version (expected 3, got 4)

### ISSUE THREAD

**Issue by ericpyle** [ractivejs/ractive-load#39]
I cannot seem to get ractive-load to work with any version of ractive from 0.8.0 and up. (ractive version 0.7.3 works fine with ractive-load).  I'm running this in the context of electron app.

**Chrome Dev Tools Console output:**
Ractive.js 0.8.0 in debug mode, more...
index.html:56 Error: Mismatched template version (expected 3, got 4)! Please ensure you are using the latest version of Ractive.js in your build process as well as in your app
    at parse ({electron-app}\node_modules\ractive-load\dist\ractive-load.umd.js:73:10)
    at Object.make ({electron-app}\node_modules\ractive-load\dist\ractive-load.umd.js:456:16)
    at {electron-app}\node_modules\ractive-load\dist\ractive-load.umd.js:661:10
    at {electron-app}\node_modules\ractive-load\dist\ractive-load.umd.js:660:12

**index.html:56 context** 
```
var load = require('ractive-load');
load( 'ractive_components/login.html' ).then(function(Login) {...}).catch(function(error){console.log(error);});
```
Line 56 is console.log(error)

**Comment by AShynkevich** [comment]
The same situaton

**Comment by fskreuz** [comment]
Similar to https://github.com/ractivejs/rvc/issues/18#issuecomment-295712453

We're working on it. In the mean time, you can bump up the version manually. 😄

**Comment by avoto** [comment]
I haven't done a pull request, but recently I fixed both RVC and Ractive Load. You can get the Ractive Load here:
https://github.com/avoto/ractive-load/blob/master/dist/ractive-load.js
RVC:
https://github.com/avoto/rvc/blob/master/dist/rvc.js
