### ISSUE TITLE
0.8 breakage

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive-load#40]
## Description

Well aware of the current issue of ractive-load, rcu and Ractive >0.8, but just posting this one here since nobody appears to have encountered it yet. Aside from the version number, attributes are parsed to a different property (`m` instead of `a`) causing [this block](https://github.com/ractivejs/ractive-load/blob/master/dist/ractive-load.umd.js#L87) to fail parsing the rest of the component.

## Reproduction

```js
const template = '<link rel="ractive" href="path/to/Component.html">'
console.log(JSON.stringify(Ractive.parse(template)))
```

## Expected (<0.8)

```json
{"v":3,"t":[{"t":7,"e":"link","a":{"rel":"ractive","href":"path/to/Component.html"}}]}
```

## Actual (>0.8)

```json
{"v":4,"t":[{"t":7,"e":"link","m":[{"n":"rel","f":"ractive","t":13},{"n":"href","f":"path/to/Component.html","t":13}]}]}
```

**Comment by kouts** [comment]
@fskreuz does this this make ```ractive-load``` unusable for Ractive 0.9.x ?

**Comment by fskreuz** [comment]
Yep. Fell back to 0.7 which was sufficient for my needs. I haven't had time to check back on this issue.

**Comment by aesqe** [comment]
try this: https://github.com/aesqe/ractive-load, it works with the latest ractive versions
